package pom.locators;

import com.codeborne.selenide.SelenideElement;
import org.openqa.selenium.By;

import static com.codeborne.selenide.Selenide.$;

public class administration_locators {
    public static SelenideElement adminTab = $(By.xpath("//span[contains(text(), 'Administration')]"));
    public static SelenideElement refTables =$(By.xpath("/html/body/div[3]/div[2]/div/ul/li[14]/ul/li/a"));
    public static SelenideElement accolades =$(By.xpath("//a[contains(text(), 'Accolades Category')]"));
    public static SelenideElement billing =$(By.xpath("//a[contains(text(), 'Billing Frequency')]"));
    public static SelenideElement budget =$(By.xpath("//a[contains(text(), 'Budget Basis')]"));
    public static SelenideElement contractRole =$(By.xpath("//a[contains(text(), 'Contract Role (Bill Rates)')]"));
    public static SelenideElement complaintCategoty =$(By.xpath("//a[contains(text(), 'Complaint Category')]"));
    public static SelenideElement cretification =$(By.xpath("//a[contains(text(), 'Certifications')]"));
    public static SelenideElement clientContact =$(By.xpath("//a[contains(text(), 'Client Contact Interest')]"));
    public static SelenideElement clientType =$(By.xpath("//a[contains(text(), 'Client Type')]"));
    public static SelenideElement contactType =$(By.xpath("//a[contains(text(), 'Contact Type')]"));
    public static SelenideElement contractType =$(By.xpath("//a[contains(text(), 'Contract Type')]"));
    public static SelenideElement country=$(By.xpath("//a[contains(text(), 'Country')]"));
    public static SelenideElement distributionMethod =$(By.xpath("//a[contains(text(), 'Distribution Method')]"));
    public static SelenideElement division =$(By.xpath("//*[@id=\"ReferenceTablesSubMenu\"]/li[13]/a"));
    public static SelenideElement engagementFrequency =$(By.xpath("//a[contains(text(), 'Engagement Frequency')]"));
    public static SelenideElement engagementType =$(By.xpath("//a[contains(text(), 'Engagement Type')]"));
    public static SelenideElement exchangeRate =$(By.xpath("//a[contains(text(), 'Exchange Rate')]"));
    public static SelenideElement hawkEntity =$(By.xpath("//a[contains(text(), 'Hawk Entity')]"));
    public static SelenideElement inspectionType =$(By.xpath("//a[contains(text(), 'Inspection Type')]"));
    public static SelenideElement IRS =$(By.xpath("//a[contains(text(), 'IRS Mileage Rate')]"));
    public static SelenideElement jobRole =$(By.xpath("//a[contains(text(), 'Job Role (Pay Rates)')]"));
    public static SelenideElement meetingType =$(By.xpath("//a[contains(text(), 'Meeting Type')]"));
    public static SelenideElement partnerCompany =$(By.xpath("//a[contains(text(), 'Partner Company')]"));
    public static SelenideElement paymentTerms =$(By.xpath("//a[contains(text(), 'Payment Terms')]"));
    public static SelenideElement RCAReview =$(By.xpath("//a[contains(text(), 'RCA Review')]"));
    public static SelenideElement RCAStatus =$(By.xpath("//a[contains(text(), 'RCA Status')]"));
    public static SelenideElement relationshipEmergencyContact=$(By.xpath("//a[contains(text(), 'Relationship Emergency Contact')]"));
    public static SelenideElement requiredAttachment =$(By.xpath("//a[contains(text(), 'Required Attachment')]"));
    public static SelenideElement resourceClass=$(By.xpath("//a[contains(text(), 'Resource Class')]"));
    public static SelenideElement resourceType =$(By.xpath("//a[contains(text(), 'Resource Type')]"));
    public static SelenideElement safetyReq =$(By.xpath("//a[contains(text(), 'Safety Requirement')]"));
    public static SelenideElement state =$(By.xpath("//a[contains(text(), 'State')]"));
    public static SelenideElement taxonomy =$(By.xpath("//*[@id=\"ReferenceTablesSubMenu\"]/li[32]/a"));
    public static SelenideElement selectAccoladesCategory =$(By.id("dropdownlistContentddlAccoladesCategory"));
    public static SelenideElement accoladesCategory=$(By.id("txtMeetingType"));
    public static SelenideElement saveAccoladesButton =$(By.id("btnSaveAccoladesCategory"));
    public static SelenideElement selectBillingFrequency =$(By.id("dropdownlistContentddlBillingFrequency"));
    public static SelenideElement billingFrequency =$(By.id("txtBillingFrequency"));
    public static SelenideElement BillingOther =$(By.xpath("//*[@id=\"niBillingFrequencyOrderIndex\"]"));
    public static SelenideElement saveBillingFrequnecy =$(By.id("btnSaveBillingFrequency"));
    public static SelenideElement selectBudgetBasis =$(By.id("dropdownlistContentddlBudgetBasis"));
    public static SelenideElement otherBudgedBasis =$(By.xpath("//*[@id=\"niBudgetBasisOrderIndex\"]"));
    public static SelenideElement saveBudgedBasis =$(By.id("btnSaveBudgetBasis"));
    public static SelenideElement budgedBasis =$(By.id("txtBudgetBasis"));
    public static SelenideElement selectContractRole =$(By.id("dropdownlistContentddlContractRolePayRate"));
    public static SelenideElement contractRoleInput =$(By.xpath("//*[@id=\"txtContractRolePayRate\"]"));
    public static SelenideElement contractRoleInvoice =$(By.id("txtContractRolePayRate2"));
    public static SelenideElement saveClientRole =$(By.id("btnSaveContractRolePayRate"));
    public static SelenideElement selectComplaintCategory =$(By.id("dropdownlistContentddlComplaintCategory"));
    public static SelenideElement ComplaintCategoryInput =$(By.id("txtComplaintCategory"));
    public static SelenideElement complaintCategorySaveButton =$(By.id("btnSaveComplaintCategory"));
    public static SelenideElement selectCertification =$(By.id("dropdownlistContentddlCertifications"));
    public static SelenideElement certificationInput =$(By.id("txtCertifications"));
    public static SelenideElement certificationSave =$(By.id("btnSaveCertifications"));
    public static SelenideElement selectClientContact=$(By.id("dropdownlistContentddlClientContactInterest"));
    public static SelenideElement clientContactInput =$(By.id("txtClientContactInterest"));
    public static SelenideElement saveClientContact=$(By.id("btnSaveClientContactInterest"));
    public static SelenideElement selectClinetType= $(By.id("dropdownlistContentddlClientType"));
    public static SelenideElement clientTypeInput =$(By.id("txtClientType"));
    public static SelenideElement otherClinetType =$(By.xpath("//*[@id=\"niClientTypeOrderIndex\"]"));
    public static SelenideElement saveClientType=$(By.id("btnSaveClientType"));
    public static SelenideElement selectContactType =$(By.id("dropdownlistContentddlContactType"));
    public static SelenideElement contactTypeInput =$(By.id("txtContactType"));
    public static SelenideElement saveContactType =$(By.id("btnSaveContactType"));
    public static SelenideElement selectContractType =$(By.id("dropdownlistContentddlContractType"));
    public static SelenideElement contractTypeInput =$(By.id("txtContractType"));
    public static SelenideElement saveContractType = $(By.id("btnSaveContractType"));
    public static SelenideElement selectCountry =$(By.xpath("//*[@id=\"dropdownlistContentddlCountry\"]"));
    public static SelenideElement countryInput =$(By.xpath("//*[@id=\"txtCountry\"]"));
    public static SelenideElement countryPhoneCode =$(By.id("txtCountry2"));
    public static SelenideElement countryCurrecnyCode =$(By.id("dropdownlistContentddlCountry3"));
    public static SelenideElement countryCurrencySign =$(By.id("txtCountry4"));
    public static SelenideElement countryOrder=$(By.xpath("//*[@id=\"niCountryOrderIndex\"]"));
    public static SelenideElement saveCountry=$(By.xpath("//*[@id=\"btnSaveCountry\"]"));
    public static SelenideElement selectDistributionMethod=$(By.id("dropdownlistContentddlDistributionMethod"));
    public static SelenideElement distributionMethodInput =$(By.id("txtDistributionMethod"));
    public static SelenideElement distributionOther =$(By.xpath("//*[@id=\"niDistributionMethodOrderIndex\"]"));
    public static SelenideElement saveDistribution =$(By.id("btnSaveDistributionMethod"));
    public static SelenideElement selectDivision =$(By.xpath("//*[@id=\"dropdownlistContentddlDivision\"]"));
    public static SelenideElement divisionInput =$(By.id("txtDivision"));
    public static SelenideElement selectSageDivision =$(By.id("dropdownlistContentddlDivision2"));
    public static SelenideElement saveDivision =$(By.id("btnSaveDivision"));
    public static SelenideElement selectEngagementFrequency=$(By.id("dropdownlistContentddlEngagementFrequency"));
    public static SelenideElement engagmentFrequencyInput =$(By.id("txtEngagementFrequency"));
    public static SelenideElement engagmentOther =$(By.xpath("//*[@id=\"niEngagementFrequencyOrderIndex\"]"));
    public static SelenideElement engagmentSave=$(By.id("btnSaveEngagementFrequency"));
    public static SelenideElement ratesSelectDate=$(By.xpath("//*[@id=\"dtiExchangeRateDate\"]"));
    public static SelenideElement rateUnit =$(By.xpath("//*[@id='txtExchangeRateUSD']"));
    public static SelenideElement AED =$(By.xpath("//*[@id='txtExchangeRateAED']"));
    public static SelenideElement BRL =$(By.xpath("//*[@id=\"txtExchangeRateBRL\"]"));
    public static SelenideElement EGP =$(By.xpath("//*[@id=\"txtExchangeRateEGP\"]"));
    public static SelenideElement INR =$(By.xpath("//*[@id=\"txtExchangeRateINR\"]"));
    public static SelenideElement MYR =$(By.xpath("//*[@id=\"txtExchangeRateMYR\"]"));
    public static SelenideElement SAR =$(By.xpath("//*[@id=\"txtExchangeRateSAR\"]"));
    public static SelenideElement TRY =$(By.xpath("//*[@id=\"txtExchangeRateTRY\"]"));
    public static SelenideElement ZAR =$(By.xpath("//*[@id=\"txtExchangeRateZAR\"]"));
    public static SelenideElement AOA =$(By.xpath("//*[@id=\"txtExchangeRateAOA\"]"));
    public static SelenideElement CAD =$(By.xpath("//*[@id=\"txtExchangeRateCAD\"]"));
    public static SelenideElement EUR =$(By.xpath("//*[@id=\"txtExchangeRateEUR\"]"));
    public static SelenideElement JPY =$(By.xpath("//*[@id=\"txtExchangeRateJPY\"]"));
    public static SelenideElement NGN =$(By.xpath("//*[@id=\"txtExchangeRateNGN\"]"));
    public static SelenideElement SEK =$(By.xpath("//*[@id=\"txtExchangeRateSEK\"]"));
    public static SelenideElement TTD =$(By.xpath("//*[@id=\"txtExchangeRateTTD\"]"));
    public static SelenideElement ARS =$(By.xpath("//*[@id=\"txtExchangeRateARS\"]"));
    public static SelenideElement CNY =$(By.xpath("//*[@id=\"txtExchangeRateCNY\"]"));
    public static SelenideElement GBP =$(By.xpath("//*[@id=\"txtExchangeRateGBP\"]"));
    public static SelenideElement KRW =$(By.xpath("//*[@id=\"txtExchangeRateKRW\"]"));
    public static SelenideElement NOK =$(By.xpath("//*[@id=\"txtExchangeRateNOK\"]"));
    public static SelenideElement SGD=$(By.xpath("//*[@id=\"txtExchangeRateSGD\"]"));
    public static SelenideElement VEF =$(By.xpath("//*[@id=\"txtExchangeRateVEF\"]"));
    public static SelenideElement AUD =$(By.xpath("//*[@id=\"txtExchangeRateAUD\"]"));
    public static SelenideElement COP =$(By.xpath("//*[@id=\"txtExchangeRateCOP\"]"));
    public static SelenideElement IDR =$(By.xpath("//*[@id=\"txtExchangeRateIDR\"]"));
    public static SelenideElement MXN =$(By.xpath("//*[@id=\"txtExchangeRateMXN\"]"));
    public static SelenideElement RUB =$(By.xpath("//*[@id=\"txtExchangeRateRUB\"]"));
    public static SelenideElement THB =$(By.xpath("//*[@id=\"txtExchangeRateTHB\"]"));
    public static SelenideElement VND =$(By.xpath("//*[@id=\"txtExchangeRateVND\"]"));
    public static SelenideElement exchangeRateSaveButton =$(By.id("btnSaveExchangeRate"));
    public static SelenideElement selectHawkEntity =$(By.xpath("//*[@id=\"dropdownlistWrapperddlHawkEntity\"]"));
    public static SelenideElement hawkEntityRelationship =$(By.xpath("//*[@id=\"txtHawkEntity\"]"));
    public static SelenideElement hawkEntityName =$(By.id("txtHawkEntityName"));
    public static SelenideElement hawkEntityAddress =$(By.id("txtHawkEntityAddress"));
    public static SelenideElement hawkEntityCity =$(By.id("txtHawkEntityCity"));
    public static SelenideElement hawkEntityState =$(By.id("dropdownlistWrapperddlHawkEntityState"));
    public static SelenideElement hawkEntityPostalCode =$(By.id("txtHawkEntityPostalCode"));
    public static SelenideElement hawkEntityCountry =$(By.id("dropdownlistWrapperddlHawkEntityCountry"));
    public static SelenideElement hawkEntityDefaultCurrency =$(By.id("dropdownlistContentddlHawkEntityCurrency"));
    public static SelenideElement hawkEntityOrder=$(By.xpath("//*[@id=\"niHawkEntityOrderIndex\"]"));
    public static SelenideElement hawkEntitySaveButton =$(By.id("btnSaveHawkEntity"));
    public static SelenideElement selectInspectionType=$(By.id("dropdownlistWrapperddlInspectionType"));
    public static SelenideElement inspectionTypeInput =$(By.id("txtInspectionType"));
    public static SelenideElement saveInspectionType =$(By.id("btnSaveInspectionType"));
    public static SelenideElement reComputeMileageRates =$(By.id("btnRecomputeMileageRates"));
    public static SelenideElement addLineButton =$(By.id("btnAddAddMileageRateLine"));
    public static SelenideElement IRSsaveButton =$(By.id("btnSaveIrsMileageRate"));
    public static SelenideElement IRSForm =$(By.id("contentgridIrsMileageRate"));
    public static SelenideElement selectJobRole =$(By.id("dropdownlistContentddlJobRole"));
    public static SelenideElement jobRoleInput =$(By.id("txtJobRole"));
    public static SelenideElement jobRoleSave =$(By.id("btnSaveJobRole"));
    public static SelenideElement selectMeetingType =$(By.id("dropdownlistContentddlMeetingType"));
    public static SelenideElement meetingTypeInput =$(By.id("txtMeetingType"));
    public static SelenideElement meetingTypeSave =$(By.id("btnSaveMeetingType"));
    public static SelenideElement selectPartnerCompany=$(By.id("dropdownlistContentddlPartnerCompany"));
    public static SelenideElement partnerCompanyInput =$(By.id("txtPartnerCompany"));
    public static SelenideElement partnerCompanySave =$(By.id("btnSavePartnerCompany"));
    public static SelenideElement selectPaymentTerms =$(By.id("dropdownlistContentddlPaymentTerms"));
    public static SelenideElement paymentTermsInput =$(By.id("txtPaymentTerms"));
    public static SelenideElement paymentTermsDays =$(By.xpath("//*[@id=\"niPaymentTerms2\"]"));
    public static SelenideElement paymentTermsOther =$(By.xpath("//*[@id=\"niPaymentTermsOrderIndex\"]"));
    public static SelenideElement paymentTermsSave =$(By.id("btnSavePaymentTerms"));
    public static SelenideElement selectRCAreview=$(By.id("dropdownlistWrapperddlRCAReview"));
    public static SelenideElement RCAreviewInput=$(By.id("txtRCAReview"));
    public static SelenideElement RCAreviewOther =$(By.xpath("//*[@id=\"niRCAReviewOrderIndex\"]"));
    public static SelenideElement RCAsave =$(By.id("btnSaveRCAReview"));
    public static SelenideElement selectRCAstatus =$(By.xpath("//*[@id=\"ddlRCAStatus\"]"));
    public static SelenideElement RCAstatusInput =$(By.id("txtRCAStatus"));
    public static SelenideElement RCAstatusOther =$(By.xpath("//*[@id=\"niRCAStatusOrderIndex\"]"));
    public static SelenideElement RCAstatusSave =$(By.id("btnSaveRCAStatus"));
    public static SelenideElement selectReleationshipEmergencyContact =$(By.id("dropdownlistContentddlEmergencyContRelationship"));
    public static SelenideElement relEmerContInput=$(By.id("txtEmergencyContRelationship"));
    public static SelenideElement relEmerContOther =$(By.xpath("//*[@id=\"niEmergencyContRelationshipOrderIndex\"]"));
    public static SelenideElement relEmerContSave =$(By.id("btnSaveEmergencyContRelationship"));
    public static SelenideElement selectRequiredAttachment =$(By.id("dropdownlistContentddlRequiredAttachment"));
    public static SelenideElement requiredAttachmentInput =$(By.id("txtRequiredAttachment"));
    public static SelenideElement requiredAttachmentOther =$(By.xpath("//*[@id=\"niRequiredAttachmentOrderIndex\"]"));
    public static SelenideElement requiredAttachmentSave =$(By.id("btnSaveRequiredAttachment"));
    public static SelenideElement selectResourceClass =$(By.xpath("//*[@id=\"ddlResourceClass\"]"));
    public static SelenideElement resourceClassInput =$(By.id("txtResourceClass"));
    public static SelenideElement resourceClassOther =$(By.xpath("//*[@id=\"niResourceClassOrderIndex\"]"));
    public static SelenideElement resourceClassSave =$(By.id("btnSaveResourceClass"));
    public static SelenideElement selectResourceType = $(By.id("dropdownlistContentddlResourceType"));
    public static SelenideElement resourceTypeInput =$(By.xpath("//*[@id=\"txtResourceType\"]"));
    public static SelenideElement recourceBurdenFactor =$(By.id("txtResourceType2"));
    public static SelenideElement resourceOther =$(By.xpath("//*[@id=\"niResourceTypeOrderIndex\"]"));
    public static SelenideElement saveResourceType =$(By.id("btnSaveResourceType"));
    public static SelenideElement selectSafteyRequiremant=$(By.id("dropdownlistContentddlSafetyRequirement"));
    public static SelenideElement safetyReqInput =$(By.id("txtSafetyRequirement"));
    public static SelenideElement saveSafetyReq =$(By.id("btnSaveSafetyRequirement"));
    public static SelenideElement selectCountryState =$(By.id("dropdownlistContentddlParentCountryState"));
    public static SelenideElement selectState=$(By.id("dropdownlistContentddlCountryState"));
    public static SelenideElement stateInput =$(By.xpath("//*[@id=\"txtCountryState\"]"));
    public static SelenideElement codeInput =$(By.id("txtCountryState2"));
    public static SelenideElement saveState =$(By.id("btnSaveCountryState"));
    public static SelenideElement selectTaxaonomy =$(By.id("dropdownlistContentddlTaxonomy"));
    public static SelenideElement taxNumber =$(By.xpath("//*[@id=\"niTaxonomyNumber\"]"));
    public static SelenideElement taxPrimaryGroup =$(By.id("txtTaxonomyPrimaryGroup"));
    public static SelenideElement taxSubGroup =$(By.id("txtTaxonomySubGroup"));
    public static SelenideElement tax3rdLevel =$(By.id("txtTaxonomy3rdLevel"));
    public static SelenideElement taxSave =$(By.id("btnSaveTaxonomy"));
    public static SelenideElement nextMenu = $(By.xpath("//*[@id=\"top-menu\"]/div/ul/li[16]/a"));

    }

