package pom.locators;

import com.codeborne.selenide.SelenideElement;
import org.openqa.selenium.By;

import static com.codeborne.selenide.Selenide.$;

public class reporting_locators {
    public static SelenideElement reportTap = $(By.xpath("//span[contains(text(), 'Reporting')]"));
    public static SelenideElement biliableManhoursByDivision = $(By.xpath("//a[contains(text(), 'Billable')]"));
    public static SelenideElement grossMargin = $(By.xpath("//a[contains(text(), 'Gross Margin')]"));
    public static SelenideElement invoice = $(By.xpath("/html/body/div[3]/div[2]/div/ul/li[12]/ul/li[3]/a"));
    public static SelenideElement manhoursbyClientJob = $(By.xpath("//a[contains(text(), 'Manhours by Client/Job')]"));
    public static SelenideElement miliage = $(By.xpath("//*[@id='top-menu']/div/ul/li[12]/ul/li[7]/a"));
    public static SelenideElement newhireReport = $(By.xpath("//a[contains(text(), 'New Hire Report')]"));
    public static SelenideElement payroll = $(By.xpath("//a[contains(text(), 'Payroll')]"));
    public static SelenideElement performaceEvents = $(By.xpath("//a[contains(text(), 'Performance Events')]"));
    public static SelenideElement revenueAccuralReport = $(By.xpath("//a[contains(text(), 'Revenue Accrual Report')]"));
    public static SelenideElement revenueApportionmentRepport = $(By.xpath("//a[contains(text(), 'Revenue Apportionment Report')]"));
    public static SelenideElement terminatingEmployeeReport = $(By.xpath("// a[contains(text(), 'Terminating Employee Report')]"));

    public static SelenideElement utilization = $(By.xpath("//a[contains(text(), 'Utilization')]"));
    public static SelenideElement taxonomyReport = $(By.xpath("// a[contains(text(), 'Taxonomy Report')]"));
    public static SelenideElement biliableManhoursByDivisionYear = $(By.xpath("//*[@id='ddlYear']"));
    public static SelenideElement biliableManhoursByDivisionHawkEntity = $(By.id("dropdownlistWrapperddlHawkEntity"));
    public static SelenideElement biliableManhoursByDivisionViewButon = $(By.id("btnView"));
    public static SelenideElement biliableManhoursByDivisionExportButton = $(By.id("btnExportToExcel"));
    public static SelenideElement grossMarginClient = $(By.id("dropdownlistWrapperddlClient"));
    public static SelenideElement grossMarginDivision = $(By.xpath("//*[@id=\"ddlHawkDivision\"]"));
    public static SelenideElement grossMarginJobStatus = $(By.xpath("//*[@id=\"ddlJobStatus\"]"));
    public static SelenideElement grossMarginSearch = $(By.id("txtSearchKey"));
    public static SelenideElement grossMarginViewButton = $(By.id("btnView"));
    public static SelenideElement grossMarginExportButton = $(By.id("btnExportToExcel"));
    public static SelenideElement invoiceStartDate = $(By.xpath("//*[@id=\"dtiDateFrom\"]"));
    public static SelenideElement invoiceEndDate = $(By.xpath("//*[@id=\"dtiDateTo\"]"));
    public static SelenideElement invoiceEntity = $(By.id("dropdownlistWrapperddlHawkEntity"));
    public static SelenideElement invoiceDivision = $(By.xpath("//*[@id=\"ddlHawkDivision\"]"));
    public static SelenideElement invoiceClient = $(By.xpath("//*[@id=\"ddlClient\"]"));
    public static SelenideElement invoiceContractType = $(By.xpath("//*[@id=\"ddlContractType\"]"));
    public static SelenideElement invoiceSearch = $(By.id("txtSearchKey"));
    public static SelenideElement invoiceViewButton = $(By.id("btnView"));
    public static SelenideElement invoiceExportButton = $(By.id("btnExportToExcel"));
    public static SelenideElement invoiceCoordinator = $(By.xpath("//*[@id=\"ddlCoordinator\"]"));
    public static SelenideElement manhoursbyClientJobStartDate = $(By.xpath("//*[@id=\"dtiDateFrom\"]"));
    public static SelenideElement manhoursbyClientJobEndDate = $(By.xpath("//*[@id=\"dtiDateTo\"]"));
    public static SelenideElement manhoursbyClientJobHawkEntity = $(By.id("dropdownlistContentddlHawkEntity"));
    public static SelenideElement manhoursbyClientJobDivision = $(By.id("dropdownlistContentddlHawkDivision"));
    public static SelenideElement manhoursbyClientJobResourceType = $(By.id("dropdownlistContentddlResourceType"));
    public static SelenideElement manhoursbyClientJobResourceClass = $(By.id("dropdownlistContentddlResourceClass"));
    public static SelenideElement manhoursbyClientJobClient = $(By.id("dropdownlistContentddlClient"));
    public static SelenideElement manhoursbyClientJob_Job = $(By.id("dropdownlistContentddlJobNumber"));
    public static SelenideElement manhoursbyClientJobResource = $(By.id("dropdownlistContentddlResources"));
    public static SelenideElement manhoursbyClientJobSearch = $(By.id("txtSearchKey"));
    public static SelenideElement manhoursbyClientJobViewButton = $(By.id("btnView"));
    public static SelenideElement manhoursbyClientJobExportButton = $(By.id("btnExportToExcel"));
    public static SelenideElement mileageYear = $(By.xpath("//*[@id=\"dropdownlistContentddlYear\"]"));
    public static SelenideElement mileageEntity = $(By.id("dropdownlistContentddlHawkEntity"));
    public static SelenideElement mileageDivision = $(By.id("dropdownlistContentddlHawkDivision"));
    public static SelenideElement mileageClient = $(By.id("dropdownlistContentddlClient"));
    public static SelenideElement mileageViewButton = $(By.id("btnView"));
    public static SelenideElement mileageExportButton = $(By.id("btnExportToExcel"));
    public static SelenideElement newHireReportStaerDate = $(By.xpath("//*[@id=\"dtiDateFrom\"]"));
    public static SelenideElement newHireReportEndDate = $(By.xpath("//*[@id=\"inputdtiDateTo\"]"));
    public static SelenideElement newHireReportSearch = $(By.id("txtSearchKey"));
    public static SelenideElement newHireReportViewButton = $(By.id("btnView"));
    public static SelenideElement newHireReportExportButton = $(By.id("btnExportToExcel"));
    public static SelenideElement payrollPeriod = $(By.xpath("//*[@id=\"ddlPayrollPeriods\"]"));
    public static SelenideElement payrollResourceType = $(By.id("dropdownlistContentddlPayrollResourceTypes"));
    public static SelenideElement payrollEntity = $(By.id("dropdownlistContentddlHawkEntity"));
    public static SelenideElement payrollDivision = $(By.id("dropdownlistContentddlHawkDivision"));
    public static SelenideElement payrollResource = $(By.id("dropdownlistContentddlResourcesForPayroll"));
    public static SelenideElement payrollDetail_summary = $(By.id("dropdownlistContentddlDetailSummary"));
    public static SelenideElement payrollViewButton = $(By.id("btnView"));
    public static SelenideElement payrollExportExel = $(By.id("btnExportToExcel"));
    public static SelenideElement payrollExportPDF = $(By.id("btnExportToPDF"));
    public static SelenideElement performanceStartDate = $(By.xpath("//*[@id=\"dtiDateFrom\"]"));
    public static SelenideElement performanceEndDate = $(By.xpath("//*[@id=\"inputdtiDateTo\"]"));
    public static SelenideElement performanceClient = $(By.id("dropdownlistWrapperddlClient"));
    public static SelenideElement performanceNCR = $(By.id("dropdownlistContentddlNCR"));
    public static SelenideElement performanceEntity = $(By.id("dropdownlistContentddlHawkEntity"));
    public static SelenideElement performanceDivision = $(By.id("dropdownlistContentddlHawkDivision"));
    public static SelenideElement performanceType = $(By.id("dropdownlistContentddlPerformanceType"));
    public static SelenideElement performanceCategory = $(By.id("dropdownlistContentddlCategory"));
    public static SelenideElement performanceSearch = $(By.id("txtSearchKey"));
    public static SelenideElement performanceViewButton = $(By.id("btnView"));
    public static SelenideElement performanceExportButton = $(By.id("btnExportToExcel"));
    public static SelenideElement revenueStartDate = $(By.xpath("//*[@id=\"inputdtiDateFrom\"]"));
    public static SelenideElement revenueEndDate = $(By.xpath("//*[@id=\"inputdtiDateTo\"]"));
    public static SelenideElement revenueDivision = $(By.id("dropdownlistWrapperddlHawkDivision"));
    public static SelenideElement revenueCoordinator = $(By.id("dropdownlistContentddlCoordinator"));
    public static SelenideElement revenueClient = $(By.id("dropdownlistContentddlClient"));
    public static SelenideElement revenuePrimaryWork = $(By.id("dropdownlistContentddlPrimaryWorkLocation"));
    public static SelenideElement revenueHawkEntity = $(By.id("dropdownlistWrapperddlHawkEntity"));
    public static SelenideElement revenueSearch = $(By.id("txtSearchKey"));
    public static SelenideElement revenueViewButton = $(By.id("btnView"));
    public static SelenideElement revenueExportButton = $(By.id("btnExportToExcel"));
    public static SelenideElement apportionmnetStartDate = $(By.xpath("//*[@id=\"inputdtiDateFrom\"]"));
    public static SelenideElement apportionmnetEndDate = $(By.xpath("//*[@id=\"inputdtiDateTo\"]"));
    public static SelenideElement apportionmnetHawkEntity = $(By.id("dropdownlistWrapperddlHawkEntity"));
    public static SelenideElement apportionmnetCoordinator = $(By.id("dropdownlistContentddlCoordinator"));
    public static SelenideElement apportionmnetClient = $(By.id("dropdownlistContentddlClient"));
    public static SelenideElement apportionmnetPrimaryWork = $(By.id("dropdownlistContentddlPrimaryWorkLocation"));
    public static SelenideElement apportionmnetSearch = $(By.id("txtSearchKey"));
    public static SelenideElement apportionmnetViewButton = $(By.id("btnView"));
    public static SelenideElement apportionmnetExportButton = $(By.id("btnExportToExcel"));
    public static SelenideElement terminatingStartDate = $(By.xpath("//*[@id=\"inputdtiDateFrom\"]"));
    public static SelenideElement terminatingEndDate = $(By.xpath("//*[@id=\"inputdtiDateTo\"]"));
    public static SelenideElement terminatingSerach = $(By.id("txtSearchKey"));
    public static SelenideElement terminatingViewButton = $(By.id("btnView"));
    public static SelenideElement terminatingExportButton = $(By.id("btnExportToExcel"));
    public static SelenideElement utilizationStartDate = $(By.xpath("//*[@id='inputdtiDateFrom']"));
    public static SelenideElement utilizationEndDate = $(By.xpath("//*[@id=\"inputdtiDateTo\"]"));
    public static SelenideElement utilizationHawkEntity = $(By.id("dropdownlistContentddlHawkEntity"));
    public static SelenideElement utilizationDivision = $(By.id("dropdownlistContentddlHawkDivision"));
    public static SelenideElement utilizationResourceType = $(By.id("dropdownlistContentddlResourceType"));
    public static SelenideElement utilizationResourceClass = $(By.id("dropdownlistContentddlResourceClass"));
    public static SelenideElement utilizationSerach = $(By.id("txtSearchKey"));
    public static SelenideElement utilizationResource = $(By.id("dropdownlistContentddlResources"));
    public static SelenideElement utilizationViewButton = $(By.id("btnView"));
    public static SelenideElement utilizationExportButton = $(By.id("btnExportToExcel"));
    public static SelenideElement taxonomyClient = $(By.id("dropdownlistContentddlClient"));
    public static SelenideElement taxonomyEntity = $(By.id("dropdownlistContentddlHawkEntity"));
    public static SelenideElement taxonomyDivision = $(By.id("dropdownlistContentddlHawkDivision"));
    public static SelenideElement taxonomy = $(By.id("dropdownlistContentddlTaxonomy"));
    public static SelenideElement taxonomyPrimaryGroup = $(By.id("dropdownlistContentddlPrimaryGroup"));
    public static SelenideElement taxonomySubGroup = $(By.id("dropdownlistContentddlSubGroup"));
    public static SelenideElement taxonomy3rdLevel = $(By.id("dropdownlistContentddl3rdLevel"));
    public static SelenideElement taxonomyViewButton = $(By.id("btnView"));
    public static SelenideElement taxonomyExportButton = $(By.id("btnExportToExcel"));
    public static SelenideElement taxonomySerach = $(By.id("txtSearchKey"));
}
